# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(name: "Shawn")
User.create(name: "May")
User.create(name: "Amanda")
User.create(name: "Stephany")
User.create(name: "Hephany")
User.create(name: "Lee")
User.create(name: "Christian")

Recipe.create(name: "Chicken Noodle Soup", user_id: 2)
Recipe.create(name: "Rice Cake", user_id: 4)
Recipe.create(name: "Power Protein Bar", user_id: 1)
Recipe.create(name: "Cold Frosted Flake", user_id: 6)
Recipe.create(name: "Grilled Cheese", user_id: 3)
Recipe.create(name: "Orange Chicken", user_id: 5)
Recipe.create(name: "Beef Tartar", user_id: 7)
Recipe.create(name: "Dumplings", user_id: 2)
Recipe.create(name: "Pizza", user_id: 2)
Recipe.create(name: "Cod Filet", user_id: 4)
Recipe.create(name: "Impossible Burger", user_id: 3)
Recipe.create(name: "Lasagna", user_id: 1)

Ingredient.create(name: "carrot")
Ingredient.create(name: "tomato")
Ingredient.create(name: "artichoke")
Ingredient.create(name: "potato")
Ingredient.create(name: "cabbage")
Ingredient.create(name: "durian")
Ingredient.create(name: "squash")
Ingredient.create(name: "cucumber")
Ingredient.create(name: "jicama")
Ingredient.create(name: "zucchini")
Ingredient.create(name: "edamame")
Ingredient.create(name: "asparagus")
Ingredient.create(name: "peas")
Ingredient.create(name: "beans")
Ingredient.create(name: "garlic")
Ingredient.create(name: "rice")
Ingredient.create(name: "pasta")
Ingredient.create(name: "cheese")
Ingredient.create(name: "flour")
Ingredient.create(name: "salt")
Ingredient.create(name: "pepper")

UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))
UserAllergen.create(user_id: rand(1..7), ingredient_id: rand(1..20))

RecipeIngredient.create(recipe_id: 1, ingredient_id: 20, quantity: 5)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 19, quantity: 5)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 18, quantity: 5)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 17, quantity: 5)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 16, quantity: 5)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 15, quantity: 5)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 14, quantity: 5)
RecipeIngredient.create(recipe_id: 8, ingredient_id: 13, quantity: 4)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 12, quantity: 4)
RecipeIngredient.create(recipe_id: 10, ingredient_id: 11, quantity: 4)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 10, quantity: 4)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 9, quantity: 4)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 8, quantity: 4)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 7, quantity: 4)
RecipeIngredient.create(recipe_id: 10, ingredient_id: 6, quantity: 4)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 5, quantity: 3)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 4, quantity: 3)
RecipeIngredient.create(recipe_id: 8, ingredient_id: 3, quantity: 3)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 2, quantity: 3)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 1, quantity: 3)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 2, quantity: 3)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 3, quantity: 3)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 3, quantity: 3)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 4, quantity: 3)
RecipeIngredient.create(recipe_id: 1, ingredient_id: 5, quantity: 2)
RecipeIngredient.create(recipe_id: 1, ingredient_id: 6, quantity: 2)
RecipeIngredient.create(recipe_id: 1, ingredient_id: 7, quantity: 2)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 6, quantity: 2)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 4, quantity: 2)
RecipeIngredient.create(recipe_id: 3, ingredient_id: 18, quantity: 2)
RecipeIngredient.create(recipe_id: 4, ingredient_id: 17, quantity: 2)
RecipeIngredient.create(recipe_id: 5, ingredient_id: 16, quantity: 1)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 11, quantity: 1)
RecipeIngredient.create(recipe_id: 6, ingredient_id: 14, quantity: 1)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 13, quantity: 1)
RecipeIngredient.create(recipe_id: 8, ingredient_id: 12, quantity: 1)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 11, quantity: 1)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 10, quantity: 1)
RecipeIngredient.create(recipe_id: 9, ingredient_id: 2, quantity: 1)
RecipeIngredient.create(recipe_id: 10, ingredient_id: 5, quantity: 5)
RecipeIngredient.create(recipe_id: 10, ingredient_id: 4, quantity: 5)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 3, quantity: 4)
RecipeIngredient.create(recipe_id: 11, ingredient_id: 2, quantity: 4)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 1, quantity: 3)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 17, quantity: 3)
RecipeIngredient.create(recipe_id: 12, ingredient_id: 16, quantity: 2)
RecipeIngredient.create(recipe_id: 1, ingredient_id: 12, quantity: 2)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 13, quantity: 1)
RecipeIngredient.create(recipe_id: 2, ingredient_id: 12, quantity: 1)
RecipeIngredient.create(recipe_id: 7, ingredient_id: 20, quantity: 1)
